name: build_paper

on:
  push:
    branches:
      - main
    paths:
      - src/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./paper
          root_file: atlas.tex
          extra_system_packages: fontawesome5

      - name: Move pdf
        run: |
          mkdir public
          ls
          ls paper
          mv src/atlas.pdf src/atlas.pdf
          ls src

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: main.pdf
          path: src/atlas.pdf # or path/to/artifact

#      - name: Deploy 🚀
#        uses: JamesIves/github-pages-deploy-action@releases/v3
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          BRANCH: gh-pages
#          FOLDER: public
#          CLEAN: true
